name: workflow-testing

on:
  push:
    tags:
      - 'nnef-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        run: echo "Test workflow triggered!"
